apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-api-dev
  namespace: portfolio-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-api-dev
  template:
    metadata:
      labels:
        app: portfolio-api-dev
    spec:
      containers:
      - name: api
        image: portfolio-api:dev
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__Redis
          value: "redis-service:6379"
        - name: Github__Token
          value: ""
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-api-service-dev
  namespace: portfolio-dev
spec:
  selector:
    app: portfolio-api-dev
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30081
  type: NodePort
