apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend-dev
  namespace: portfolio-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-frontend-dev
  template:
    metadata:
      labels:
        app: portfolio-frontend-dev
    spec:
      containers:
      - name: frontend
        image: portfolio-frontend:dev
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend-service-dev
  namespace: portfolio-dev
spec:
  selector:
    app: portfolio-frontend-dev
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082
  type: NodePort
