services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - portfolio-network

 
  ghost:
    image: ghost:alpine
    ports:
      - "30080:2368"
    environment:
      - database__client=sqlite3
      - database__connection__filename=/var/lib/ghost/content/data/ghost.db
      - url=http://localhost:30080
      - server__host=0.0.0.0
      - server__port=2368
    volumes:
      - ghost_data:/var/lib/ghost/content
    networks:
      - portfolio-network

  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "30081:8080"
    environment:
      - ConnectionStrings__Redis=redis:6379
      - Github__Token=${GITHUB_TOKEN}
      - SignalR__HubUrl=http://localhost:30081/portfolioHub
    depends_on:
      - redis
    networks:
      - portfolio-network

  frontend:
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
      - "30082:80"
    depends_on:
      - api
    networks:
      - portfolio-network

volumes:
  ghost_data:

networks:
  portfolio-network:
    driver: bridge
