# Development-specific docker-compose configuration
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
      target: build  # Use build stage for development
    ports:
      - "30081:8080"
    environment:
      - ConnectionStrings__Redis=redis:6379
      - Ollama__BaseUrl=http://ollama:11434
      - Ollama__Model=llama3.2
      - Github__Token=${GITHUB_TOKEN:-}
      - SignalR__HubUrl=http://localhost:30081/portfolioHub
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    volumes:
      # Mount source code for hot reload
      - ./API:/src
      - /src/bin
      - /src/obj
    depends_on:
      - redis
      - ollama
    command: ["dotnet", "watch", "run", "--urls", "http://+:8080"]

  frontend:
    build:
      context: .
      dockerfile: UI/Dockerfile.dev
    ports:
      - "30082:4200"  # Angular dev server port
    volumes:
      # Mount source code for hot reload
      - ./UI:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - NODE_ENV=development
