apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-api
  namespace: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-api
  template:
    metadata:
      labels:
        app: portfolio-api
    spec:
      containers:
      - name: api
        image: your-registry/portfolio-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__Redis
          value: "redis-service:6379"
        - name: Ollama__BaseUrl
          value: "http://ollama-service:11434"
        - name: Github__Token
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: token
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-api-service
  namespace: portfolio
spec:
  selector:
    app: portfolio-api
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
