apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: ghost
        image: ghost:alpine
        ports:
        - containerPort: 2368
        env:
        - name: security__staffDeviceVerification
          value: "false"
        - name: database__client
          value: "sqlite3"
        - name: database__connection__filename
          value: "/var/lib/ghost/content/data/ghost.db"
        - name: url
          value: "https://blog.ryanflores.dev"
        - name: server__host
          value: "0.0.0.0"
        - name: server__port
          value: "2368"
        - name: server__trustProxy
          value: "true"
        - name: url__protocol
          value: "https"
        - name: url__host
          value: "blog.ryanflores.dev"
        - name: members__api__url
          value: "https://blog.ryanflores.dev"
        - name: mail__transport
          value: "Direct"
        - name: mail__from
          value: "noreply@blog.ryanflores.dev"
        
        # Disable all email-related features
        - name: members__allowSelfSignup
          value: "true"
        - name: members__allowInviteOnly
          value: "false"
        - name: members__signupAccess
          value: "all"
        - name: members__inviteOnly
          value: "false"
        resources:  
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: ghost-data
          mountPath: /var/lib/ghost/content
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  namespace: portfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: portfolio
spec:
  selector:
    app: ghost
  ports:
  - port: 80
    targetPort: 2368
    nodePort: 30080
  type: NodePort
