apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: portfolio
spec:
  selector:
    app: ollama
  ports:
  - port: 11434
    targetPort: 11434
    nodePort: 30143
  type: NodePort
