name: Deploy to Digital Ocean Container Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: registry.digitalocean.com/rfportfoliocr
  API_IMAGE: portfolio-api
  FRONTEND_IMAGE: portfolio-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Digital Ocean Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: doctl
        password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Extract metadata for API
      id: meta-api
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/${{ env.API_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Extract metadata for Frontend
      id: meta-frontend
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/${{ env.FRONTEND_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push API image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./API/Dockerfile
        push: true
        tags: ${{ steps.meta-api.outputs.tags }}
        labels: ${{ steps.meta-api.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Frontend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./UI/Dockerfile
        push: true
        tags: ${{ steps.meta-frontend.outputs.tags }}
        labels: ${{ steps.meta-frontend.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output image details
      run: |
        echo "API Image: ${{ steps.meta-api.outputs.tags }}"
        echo "Frontend Image: ${{ steps.meta-frontend.outputs.tags }}"

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save Digital Ocean kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}

    - name: Update Kubernetes deployments
      run: |
        # Update API deployment
        kubectl set image deployment/portfolio-api api=registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/portfolio-api:latest -n portfolio
        
        # Update Frontend deployment
        kubectl set image deployment/portfolio-frontend frontend=registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/portfolio-frontend:latest -n portfolio
        
        # Wait for rollout to complete
        kubectl rollout status deployment/portfolio-api -n portfolio --timeout=300s
        kubectl rollout status deployment/portfolio-frontend -n portfolio --timeout=300s

    - name: Verify deployments
      run: |
        echo "API Deployment Status:"
        kubectl get deployment portfolio-api -n portfolio
        echo "Frontend Deployment Status:"
        kubectl get deployment portfolio-frontend -n portfolio
