name: Deploy Frontend to Digital Ocean

on:
  push:
    branches: [ main ]
    paths:
      - 'UI/**'
      - '.github/workflows/deploy-frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'UI/**'
      - '.github/workflows/deploy-frontend.yml'

env:
  REGISTRY: registry.digitalocean.com
  REGISTRY_NAME: rfportfoliocr
  FRONTEND_IMAGE: portfolio-frontend

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Digital Ocean Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: doctl
        password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Extract metadata for Frontend
      id: meta-frontend
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.FRONTEND_IMAGE }}
        tags: |
          type=ref,event=branch
          type=sha,prefix=main-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Frontend image
      id: build-frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./UI/Dockerfile
        push: true
        tags: ${{ steps.meta-frontend.outputs.tags }}
        labels: ${{ steps.meta-frontend.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output Frontend image details
      run: |
        echo "Frontend Image: ${{ steps.meta-frontend.outputs.tags }}"

  deploy-frontend-to-k8s:
    needs: build-and-push-frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save Digital Ocean kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}

    - name: Update Frontend deployment
      run: |
        # Update Frontend deployment with the latest tag
        kubectl set image deployment/portfolio-frontend frontend=${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/portfolio-frontend:latest -n portfolio
        
        # Wait for rollout to complete
        kubectl rollout status deployment/portfolio-frontend -n portfolio --timeout=300s

    - name: Verify Frontend deployment
      run: |
        echo "Frontend Deployment Status:"
        kubectl get deployment portfolio-frontend -n portfolio
